
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbjfbopymuomicyelpnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiamZib3B5bXVvbWljeWVscG5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2Mjk3NzIsImV4cCI6MjA2NzIwNTc3Mn0.L4CRo5lfCoTHGmicuMOhgZn1ukrKsHAIEqY-usCM_zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
